import { PlatformDefinition } from "./types";

export const PLATFORMS: Record<string, PlatformDefinition> = {
  x: {
    id: "x",
    name: "X",
    purpose: "Fast public conversation, discovery, technical ideas, short-form opinions, and network exposure.",
    formats: ["short_post", "thread", "technical_opinion", "reply", "discussion"],
    actions: ["publish", "reply", "create_thread", "create_discussion"],
    validCombinations: [
      { formatId: "short_post", actionId: "publish" },
      { formatId: "thread", actionId: "create_thread" },
      { formatId: "technical_opinion", actionId: "publish" },
      { formatId: "reply", actionId: "reply" },
      { formatId: "discussion", actionId: "create_discussion" },
    ],
    constraints: {
      maxTextLength: 280,
      supportsLongForm: false,
      supportsThreads: true,
      supportsReplies: true,
      supportsLinks: true,
      supportsImages: true,
      supportsVideo: true,
      supportsCode: false,
      supportsMarkdown: false,
      supportsPersistentContent: false,
      requiresCommunityContext: false,
      promotionSensitivity: "HIGH",
    },
    strategyRules: {
      strengths: ["short technical insights", "opinions", "discussions", "networking", "fast feedback"],
      weakUseCases: ["formal long-form documentation", "pure project documentation"],
      bestFor: ["audience building", "quick idea validation"],
      avoid: ["overly formal corporate writing", "long contextless promotion"],
    },
    goalAffinity: {
      REACH: 1.0,
      PROFILE_DISCOVERY: 0.9,
      CREDIBILITY: 0.5,
      NETWORK_GROWTH: 0.9,
      PROJECT_DISCOVERY: 0.8,
      HIRING: 0.4,
      COLLABORATION: 0.7,
      TRAFFIC: 0.6,
      COMMUNITY: 0.8,
      LEADS: 0.3,
    },
  },
  linkedin: {
    id: "linkedin",
    name: "LinkedIn",
    purpose: "Professional credibility, career-oriented distribution, engineering lessons, professional storytelling, and case studies.",
    formats: ["professional_post", "engineering_lesson", "case_study", "project_update"],
    actions: ["publish"],
    validCombinations: [
      { formatId: "professional_post", actionId: "publish" },
      { formatId: "engineering_lesson", actionId: "publish" },
      { formatId: "case_study", actionId: "publish" },
      { formatId: "project_update", actionId: "publish" },
    ],
    constraints: {
      maxTextLength: 3000,
      supportsLongForm: true,
      supportsThreads: false,
      supportsReplies: true,
      supportsLinks: true,
      supportsImages: true,
      supportsVideo: true,
      supportsCode: false,
      supportsMarkdown: false,
      supportsPersistentContent: false,
      requiresCommunityContext: false,
      promotionSensitivity: "MEDIUM",
    },
    strategyRules: {
      strengths: ["engineering lessons", "case studies", "project stories", "career/professional insights"],
      weakUseCases: ["shitposting", "unprofessional rants", "highly technical raw code dumps"],
      bestFor: ["professional networking", "career growth", "B2B leads"],
      avoid: ["overly casual tone", "unstructured thoughts"],
    },
    goalAffinity: {
      REACH: 0.8,
      PROFILE_DISCOVERY: 1.0,
      CREDIBILITY: 0.9,
      NETWORK_GROWTH: 0.9,
      PROJECT_DISCOVERY: 0.7,
      HIRING: 1.0,
      COLLABORATION: 0.6,
      TRAFFIC: 0.5,
      COMMUNITY: 0.4,
      LEADS: 0.9,
    },
  },
  peerlist: {
    id: "peerlist",
    name: "Peerlist",
    purpose: "Developer identity, project discovery, portfolio-like updates, and showcasing work.",
    formats: ["project_update", "case_study", "project_showcase"],
    actions: ["update_project", "add_case_study"],
    validCombinations: [
      { formatId: "project_update", actionId: "update_project" },
      { formatId: "project_showcase", actionId: "update_project" },
      { formatId: "case_study", actionId: "add_case_study" },
    ],
    constraints: {
      supportsLongForm: true,
      supportsThreads: false,
      supportsReplies: true,
      supportsLinks: true,
      supportsImages: true,
      supportsVideo: false,
      supportsCode: true,
      supportsMarkdown: true,
      supportsPersistentContent: true,
      requiresCommunityContext: false,
      promotionSensitivity: "LOW",
    },
    strategyRules: {
      strengths: ["project showcases", "project updates", "case studies"],
      weakUseCases: ["generic non-tech thoughts", "general news"],
      bestFor: ["showing proof of work", "getting project feedback"],
      avoid: ["spamming low-effort links"],
    },
    goalAffinity: {
      REACH: 0.5,
      PROFILE_DISCOVERY: 0.9,
      CREDIBILITY: 0.8,
      NETWORK_GROWTH: 0.7,
      PROJECT_DISCOVERY: 1.0,
      HIRING: 0.7,
      COLLABORATION: 0.8,
      TRAFFIC: 0.4,
      COMMUNITY: 0.6,
      LEADS: 0.2,
    },
  },
  github: {
    id: "github",
    name: "GitHub",
    purpose: "Technical credibility, documentation, project context, architecture, and open-source collaboration.",
    formats: ["readme", "documentation", "discussion", "release_update"],
    actions: ["update_documentation", "update_readme", "create_discussion", "release_update"],
    validCombinations: [
      { formatId: "readme", actionId: "update_readme" },
      { formatId: "documentation", actionId: "update_documentation" },
      { formatId: "discussion", actionId: "create_discussion" },
      { formatId: "release_update", actionId: "release_update" },
    ],
    constraints: {
      supportsLongForm: true,
      supportsThreads: true,
      supportsReplies: true,
      supportsLinks: true,
      supportsImages: true,
      supportsVideo: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsPersistentContent: true,
      requiresCommunityContext: false,
      promotionSensitivity: "HIGH",
    },
    strategyRules: {
      strengths: ["documentation", "architecture", "README", "discussions", "release updates"],
      weakUseCases: ["marketing copy", "personal life updates"],
      bestFor: ["technical proof", "open source collaboration"],
      avoid: ["fluff", "buzzword-heavy non-technical descriptions"],
    },
    goalAffinity: {
      REACH: 0.4,
      PROFILE_DISCOVERY: 0.7,
      CREDIBILITY: 1.0,
      NETWORK_GROWTH: 0.5,
      PROJECT_DISCOVERY: 0.9,
      HIRING: 0.8,
      COLLABORATION: 1.0,
      TRAFFIC: 0.3,
      COMMUNITY: 0.8,
      LEADS: 0.1,
    },
  },
  reddit: {
    id: "reddit",
    name: "Reddit",
    purpose: "Community discussion, technical conversations, questions, answers, and niche audiences.",
    formats: ["discussion", "question", "answer", "technical_post"],
    actions: ["post", "comment"],
    validCombinations: [
      { formatId: "discussion", actionId: "post" },
      { formatId: "question", actionId: "post" },
      { formatId: "technical_post", actionId: "post" },
      { formatId: "answer", actionId: "comment" },
    ],
    constraints: {
      supportsLongForm: true,
      supportsThreads: true,
      supportsReplies: true,
      supportsLinks: true,
      supportsImages: true,
      supportsVideo: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsPersistentContent: true,
      requiresCommunityContext: true,
      promotionSensitivity: "HIGH",
    },
    strategyRules: {
      strengths: ["questions", "answers", "technical discussions", "deep explanations"],
      weakUseCases: ["self-promotion without value", "link dropping"],
      bestFor: ["getting raw feedback", "niche community engagement"],
      avoid: ["marketing speak", "direct uncontextualized promotion"],
    },
    goalAffinity: {
      REACH: 0.7,
      PROFILE_DISCOVERY: 0.3,
      CREDIBILITY: 0.6,
      NETWORK_GROWTH: 0.2,
      PROJECT_DISCOVERY: 0.5,
      HIRING: 0.2,
      COLLABORATION: 0.4,
      TRAFFIC: 0.8,
      COMMUNITY: 0.9,
      LEADS: 0.1,
    },
  },
  blog: {
    id: "blog",
    name: "Blog",
    purpose: "Deep owned content, search-oriented knowledge, long-form technical authority.",
    formats: ["article", "deep_dive", "tutorial", "case_study"],
    actions: ["publish", "update"],
    validCombinations: [
      { formatId: "article", actionId: "publish" },
      { formatId: "article", actionId: "update" },
      { formatId: "deep_dive", actionId: "publish" },
      { formatId: "deep_dive", actionId: "update" },
      { formatId: "tutorial", actionId: "publish" },
      { formatId: "tutorial", actionId: "update" },
      { formatId: "case_study", actionId: "publish" },
      { formatId: "case_study", actionId: "update" },
    ],
    constraints: {
      supportsLongForm: true,
      supportsThreads: false,
      supportsReplies: false,
      supportsLinks: true,
      supportsImages: true,
      supportsVideo: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsPersistentContent: true,
      requiresCommunityContext: false,
      promotionSensitivity: "LOW",
    },
    strategyRules: {
      strengths: ["deep dives", "tutorials", "case studies", "evergreen content"],
      weakUseCases: ["short ephemeral thoughts", "quick questions"],
      bestFor: ["SEO", "long-term authority", "comprehensive guides"],
      avoid: ["fluff", "lack of structure"],
    },
    goalAffinity: {
      REACH: 0.6,
      PROFILE_DISCOVERY: 0.8,
      CREDIBILITY: 1.0,
      NETWORK_GROWTH: 0.4,
      PROJECT_DISCOVERY: 0.6,
      HIRING: 0.5,
      COLLABORATION: 0.3,
      TRAFFIC: 1.0,
      COMMUNITY: 0.3,
      LEADS: 0.7,
    },
  },
  portfolio: {
    id: "portfolio",
    name: "Portfolio",
    purpose: "Evergreen proof of work, case studies, project context, and professional credibility.",
    formats: ["case_study", "project_section", "architecture_decision"],
    actions: ["create_case_study", "update_project", "add_section"],
    validCombinations: [
      { formatId: "case_study", actionId: "create_case_study" },
      { formatId: "project_section", actionId: "add_section" },
      { formatId: "project_section", actionId: "update_project" },
      { formatId: "architecture_decision", actionId: "add_section" },
    ],
    constraints: {
      supportsLongForm: true,
      supportsThreads: false,
      supportsReplies: false,
      supportsLinks: true,
      supportsImages: true,
      supportsVideo: true,
      supportsCode: true,
      supportsMarkdown: true,
      supportsPersistentContent: true,
      requiresCommunityContext: false,
      promotionSensitivity: "LOW",
    },
    strategyRules: {
      strengths: ["case studies", "project pages", "architecture decisions", "project outcomes"],
      weakUseCases: ["daily updates", "unstructured thoughts"],
      bestFor: ["impressing clients or recruiters", "showcasing final outcomes"],
      avoid: ["unfinished rambling", "irrelevant personal details"],
    },
    goalAffinity: {
      REACH: 0.2,
      PROFILE_DISCOVERY: 0.9,
      CREDIBILITY: 1.0,
      NETWORK_GROWTH: 0.3,
      PROJECT_DISCOVERY: 0.8,
      HIRING: 0.9,
      COLLABORATION: 0.6,
      TRAFFIC: 0.3,
      COMMUNITY: 0.1,
      LEADS: 0.8,
    },
  }
};

export const getPlatformDefinitions = (): PlatformDefinition[] => {
  return Object.values(PLATFORMS);
};
